///
/// @Generated by Mockolo
///



import AWSS3
import AWSSDKIdentity
import Foundation
import SwiftUI
@testable import se_masked_quiz


class SERepositoryMock: SERepository {
    init() { }


    private(set) var fetchCallCount = 0
    var fetchHandler: ((Int) async throws -> [SwiftEvolution])?
    func fetch(offset: Int) async throws -> [SwiftEvolution] {
        fetchCallCount += 1
        if let fetchHandler = fetchHandler {
            return try await fetchHandler(offset)
        }
        return [SwiftEvolution]()
    }
}

actor QuizRepositoryMock: QuizRepository {
    init() { }


    private(set) var saveScoreCallCount = 0
    var saveScoreHandler: ((ProposalScore) async -> ())?
    func saveScore(_ score: ProposalScore) async {
        saveScoreCallCount += 1
        if let saveScoreHandler = saveScoreHandler {
            await saveScoreHandler(score)
        }
        
    }

    private(set) var getAllScoresCallCount = 0
    var getAllScoresHandler: (() async -> [String: ProposalScore])?
    func getAllScores() async -> [String: ProposalScore] {
        getAllScoresCallCount += 1
        if let getAllScoresHandler = getAllScoresHandler {
            return await getAllScoresHandler()
        }
        return [String: ProposalScore]()
    }

    private(set) var getScoreCallCount = 0
    var getScoreHandler: ((String) async -> ProposalScore?)?
    func getScore(for proposalId: String) async -> ProposalScore? {
        getScoreCallCount += 1
        if let getScoreHandler = getScoreHandler {
            return await getScoreHandler(proposalId)
        }
        return nil
    }

    private(set) var fetchQuizCallCount = 0
  var fetchQuizHandler: (@Sendable (String) async throws -> [Quiz])?
    func fetchQuiz(for proposalId: String) async throws -> [Quiz] {
        fetchQuizCallCount += 1
        if let fetchQuizHandler = fetchQuizHandler {
            return try await fetchQuizHandler(proposalId)
        }
        return [Quiz]()
    }

    private(set) var resetScoreCallCount = 0
    var resetScoreHandler: ((String) async -> ())?
    func resetScore(for proposalId: String) async {
        resetScoreCallCount += 1
        if let resetScoreHandler = resetScoreHandler {
            await resetScoreHandler(proposalId)
        }
        
    }
}



